version: '3.8'

services:
  # Serviço do MySQL
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Senha do root
      MYSQL_DATABASE: my_database         # Nome do banco de dados
      MYSQL_USER: my_user                 # Usuário padrão
      MYSQL_PASSWORD: my_password         # Senha do usuário
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Serviço do Laravel
  laravel:
    build:
      context: ./systock-laravel
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:PMypAVo48l1WiyQ2UE2+0IZxNc6N7oWwEIbh/K3r0m0=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: my_database
      DB_USERNAME: my_user
      DB_PASSWORD: my_password
    ports:
      - "8000:8000"
    volumes:
      - ./systock-laravel:/var/www
    command: >
      sh -c "composer install &&
             php artisan key:generate &&
             php artisan migrate --force &&
             php artisan serve --host=0.0.0.0 --port=8000"

  # Serviço do Vue.js
  vue:
    build:
      context: ./systock-vue  
      dockerfile: Dockerfile
    container_name: vue_app
    restart: always
    depends_on:
      laravel:
        condition: service_started
    ports:
      - "8081:8081"
    volumes:
      - ./systock-vue:/app  
    command: >
      sh -c "npm install &&
             npm run serve"

volumes:
  db_data:
